import Wrapper from "@/components/Wrapper";
import "@fontsource/montserrat";
import "@fontsource/montserrat/700.css";
import "@fontsource/quicksand";
import "@fontsource/quicksand/600.css";
import "./globals.css";

export const metadata = {
  title: "embedo.ai",
  description: "Generated by create next app",
  icons: {
    icon: "/images/chip.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
